### ISSUE TITLE
Update dist packages

### ISSUE THREAD

**Issue by ctomczyk** [fayway/ractive-router#1]
Hi.

The `/dist/` packages doesn't contains changes from sources (missing `go` and `replace` methods). I've run `npm run build:umd` (for umd package) and `/dist/` is now fine. Would you mind to rebuild packages and update `/dist/` packages here? Thank you.

**Comment by fayway** [comment]
Hi, I just pushed the new `dist`

**Comment by ctomczyk** [comment]
Thank you. Closing this ticket.
One more thing: do release so that dist files can be fetched e.g. using bower.
